replicaCount: 1

image:
  repository: mhdkarimi/cicd-with-argocd
  tag: "292bcf7b33aeb81a97420948278c41e71d268c89"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

containerPort: 8000

resources: {}
